services:
  mariadb:
    image: bitnami/mariadb:latest
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=CAMBIA_ROOT_DB
      - MARIADB_DATABASE=moodle
      - MARIADB_USER=moodle
      - MARIADB_PASSWORD=CAMBIA_DB_PASS
    volumes:
      - moodle_mariadb_data:/bitnami/mariadb

  moodle:
    image: erseco/alpine-moodle:latest
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      - SITE_URL=https://dawaa3-moodle-ftuk1g-1e0950-212-227-134-220.traefik.me
      - SSLPROXY=false
      - DB_TYPE=mariadb
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=moodle
      - DB_USER=moodle
      - DB_PASS=DBPASS
      - MOODLE_SITENAME=Mi Campus
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=ADMIN
      - MOODLE_EMAIL=correo@dominio.com
    volumes:
      - moodle_html_data:/var/www/html
      - moodle_data:/var/www/moodledata

volumes:
  moodle_mariadb_data:
  moodle_html_data:
  moodle_data:
